/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, BamlCtxManager, ClientRegistry, Image, Audio, Collector } from "@boundaryml/baml"
import { toBamlError } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {ComputeValue, GetWeatherReport, Message, MessageToUser, Query, Resume, Role, State, WeatherReport} from "./types"
import type TypeBuilder from "./type_builder"

export class LlmResponseParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  ChooseTools(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): (GetWeatherReport | ComputeValue | MessageToUser | Resume)[] {
    try {
      return this.runtime.parseLlmResponse(
        "ChooseTools",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as (GetWeatherReport | ComputeValue | MessageToUser | Resume)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeMessages(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string {
    try {
      return this.runtime.parseLlmResponse(
        "SummarizeMessages",
        llmResponse,
        false,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export class LlmStreamParser {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  ChooseTools(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): ((types.GetWeatherReport | null) | (types.ComputeValue | null) | (partial_types.MessageToUser | null) | (types.Resume | null) | null)[] {
    try {
      return this.runtime.parseLlmResponse(
        "ChooseTools",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as ((types.GetWeatherReport | null) | (types.ComputeValue | null) | (partial_types.MessageToUser | null) | (types.Resume | null) | null)[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  SummarizeMessages(
      llmResponse: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): string {
    try {
      return this.runtime.parseLlmResponse(
        "SummarizeMessages",
        llmResponse,
        true,
        this.ctxManager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      ) as string
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}