/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ComputeValue,  GetWeatherReport,  Message,  MessageToUser,  Query,  Resume,  Role,  State,  WeatherReport } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface ComputeValue {
        type: "compute_value"
        arithmetic_expression?: (string | null)
    }
    
    export interface GetWeatherReport {
        type: "get_weather_report"
        location?: (string | null)
    }
    
    export interface Message {
        role?: (Role | null)
        content?: (string | null)
        timestamp?: (number | null)
    }
    
    export interface MessageToUser {
        type: "message_to_user"
        message?: StreamState<(string | null)>
    }
    
    export interface Query {
        message?: (string | null)
        timestamp?: (number | null)
    }
    
    export interface Resume {
        type: "resume"
    }
    
    export interface State {
        weather_report: ((partial_types.WeatherReport | null) | null)
        recent_messages?: (partial_types.Message | null)[]
    }
    
    export interface WeatherReport {
        location?: (string | null)
        temperature?: (number | null)
        weather_status?: (string | null)
        timestamp?: (number | null)
    }
    
}