/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"

/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}


export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum Role {
  User = "User",
  Assistant = "Assistant",
  Tool = "Tool",
}

export interface ComputeValue {
  type: "compute_value"
  arithmetic_expression: string
  
}

export interface GetWeatherReport {
  type: "get_weather_report"
  location: string
  
}

export interface Message {
  role: Role
  content: string
  timestamp: number
  
}

export interface MessageToUser {
  type: "message_to_user"
  message: string
  
}

export interface Query {
  message: string
  timestamp: number
  
}

export interface Resume {
  type: "resume"
  
}

export interface State {
  weather_report?: WeatherReport | null
  recent_messages: Message[]
  
}

export interface WeatherReport {
  location: string
  temperature: number
  weather_status: string
  timestamp: number
  
}
